//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Rounds
    {
        public int Round_ID { get; set; }
        public Nullable<int> Winner_Score { get; set; }
        public string Winner { get; set; }
        public string Loser { get; set; }
        public Nullable<int> Loser_Score { get; set; }
    }
}
